export type Roles = 'admin' | 'user' | null;
export interface LoginInterface {
  username: string;
  password: string;
}
// Generated by https://quicktype.io

export interface LoginRespInterface {
  msg: string;
  username?: string;
  role?: Roles;
  token?: string;
}
// Generated by https://quicktype.io

export interface SessionTokenResp {
  msg: string;
  username?: string;
  role?: string;
  newToken?: string;
}
